[package]
name = "scir-optimize"
version = "0.1.0"
edition = "2021"
license = "BSD-3-Clause"

[dependencies]
ndarray = "0.15"
scir-core = { path = "../scir-core" }

[dev-dependencies]
ndarray-npy = "0.8"
