#!/usr/bin/env python3
"""Generate Rust source containing tabulated Bessel filter analog poles.

Runs `scipy.signal.besselap(N, norm=...)` for N in 1..=MAX_ORDER and three
normalizations (`phase`, `delay`, `mag`), writing them as `pub(crate) const`
arrays to `crates/scir-iir-filters/src/bessel_tables.rs`.

The three norms differ by a per-order rescaling of the same underlying
Bessel-polynomial roots (plus a per-norm gain `k`):

- **phase** — magnitude is `1/sqrt(2)` at ω=1; `k = 1` always; SciPy default.
- **delay** — maximally flat group delay = 1; `k = a_last` per order.
- **mag**   — `-3 dB` at ω=1; `k = norm_factor^(-N) * a_last` per order.

We tabulate poles + gain per (norm, N) so the runtime path is a `const`
slice lookup with no math required — keeps `scir-iir-filters` no_std-clean.
"""
from __future__ import annotations

import pathlib

from scipy.signal import besselap

MAX_ORDER = 25
NORMS = ["phase", "delay", "mag"]

OUT = (
    pathlib.Path(__file__).resolve().parent
    / ".."
    / "crates"
    / "scir-iir-filters"
    / "src"
    / "bessel_tables.rs"
).resolve()


def fmt_f64(x: float) -> str:
    """Format f64 with full IEEE round-trip precision."""
    # 17 significant digits losslessly round-trips f64 IEEE values.
    return f"{x:.17e}_f64"


def render_pole_array(name: str, doc: str, norm: str) -> str:
    rows: list[str] = []
    gains: list[float] = []
    for n in range(1, MAX_ORDER + 1):
        z, p, k = besselap(n, norm=norm)
        assert len(z) == 0, f"besselap({n}, {norm}): expected no zeros, got {z}"
        # Sort by (im, re) so the layout is deterministic across SciPy
        # versions (small floating-point drift can re-order otherwise).
        poles = sorted(p, key=lambda c: (c.imag, c.real))
        pole_lits = ", ".join(
            f"({fmt_f64(c.real)}, {fmt_f64(c.imag)})" for c in poles
        )
        rows.append(f"    /* N={n:>2} */ &[{pole_lits}],")
        gains.append(float(k))

    body = "\n".join(rows)
    pole_block = (
        f"/// Analog Bessel poles for orders 1..=25, {doc}.\n"
        "/// Index 0 → N=1, index 1 → N=2, ..., index 24 → N=25.\n"
        f"pub(crate) const {name}: [&[(f64, f64)]; 25] = [\n"
        f"{body}\n"
        "];\n"
    )
    gain_lits = ", ".join(fmt_f64(g) for g in gains)
    gain_block = (
        f"/// Per-order gain `k` for the {norm} normalization (orders 1..=25).\n"
        f"pub(crate) const {name}_GAINS: [f64; 25] = [{gain_lits}];\n"
    )
    return pole_block + "\n" + gain_block


def main() -> None:
    blocks = []
    blocks.append(
        render_pole_array(
            "BESSEL_AP_PHASE_POLES",
            "phase normalization (magnitude 1/sqrt(2) at ω=1; k=1 by construction)",
            "phase",
        )
    )
    blocks.append(
        render_pole_array(
            "BESSEL_AP_DELAY_POLES",
            "delay normalization (group delay = 1; k = a_last = (2N)!/(2^N N!))",
            "delay",
        )
    )
    blocks.append(
        render_pole_array(
            "BESSEL_AP_MAG_POLES",
            "magnitude normalization (-3 dB at ω=1; k = norm_factor^(-N) * a_last)",
            "mag",
        )
    )
    body = "\n".join(blocks)
    header = (
        "// Auto-generated by scripts/gen_bessel_tables.py — do not edit by hand.\n"
        "// Source: scipy.signal.besselap(N, norm='phase'|'delay'|'mag') for N=1..=25.\n"
        "// Three norms differ by a per-order rescaling of the same Bessel-polynomial\n"
        "// roots; we tabulate poles + per-norm gain `k` so runtime lookup is just a\n"
        "// `const` slice — keeps `scir-iir-filters` no_std-clean (no root-finder).\n"
        "//\n"
        "// IEEE f64 round-trips losslessly via {:.17e} formatting.\n"
        "\n"
    )
    OUT.write_text(header + body)
    print(f"wrote {OUT} ({MAX_ORDER} orders × {len(NORMS)} norms)")


if __name__ == "__main__":
    main()
