#!/usr/bin/env python3
"""Generate Rust source containing tabulated Bessel filter analog poles.

Runs `scipy.signal.besselap(N, norm='phase')` for N in 1..=MAX_ORDER and
writes them as a `pub static BESSEL_AP_PHASE: [&[(f64, f64)]; MAX_ORDER]`
table to `crates/scir-iir-filters/src/bessel_tables.rs`.

Phase normalization is SciPy's default and the only norm the scir-signal
public wrapper exposes today (delay/mag normalization are reserved for a
follow-on if needed). Source: scipy.signal._filter_design.besselap.
"""
from __future__ import annotations

import pathlib

from scipy.signal import besselap

MAX_ORDER = 25

OUT = (
    pathlib.Path(__file__).resolve().parent
    / ".."
    / "crates"
    / "scir-iir-filters"
    / "src"
    / "bessel_tables.rs"
).resolve()


def fmt_f64(x: float) -> str:
    """Format f64 with full IEEE round-trip precision."""
    # 17 significant digits losslessly round-trips f64 IEEE values.
    return f"{x:.17e}_f64"


def main() -> None:
    rows: list[str] = []
    for n in range(1, MAX_ORDER + 1):
        z, p, k = besselap(n, norm="phase")
        # z is always empty for besselap. k is always 1.0 (the gain is
        # baked into the poles for the phase-norm). Sanity-check both.
        assert len(z) == 0, f"besselap({n}): expected no zeros, got {z}"
        assert k == 1.0, f"besselap({n}): expected k=1, got {k}"
        # Sort by (im, re) so the layout is deterministic across SciPy
        # versions (small floating-point drift can re-order otherwise).
        poles = sorted(p, key=lambda c: (c.imag, c.real))
        pole_lits = ", ".join(
            f"({fmt_f64(c.real)}, {fmt_f64(c.imag)})" for c in poles
        )
        rows.append(f"    /* N={n:>2} */ &[{pole_lits}],")

    body = "\n".join(rows)
    src = (
        "// Auto-generated by scripts/gen_bessel_tables.py — do not edit by hand.\n"
        "// Source: scipy.signal.besselap(N, norm='phase') for N in 1..=25.\n"
        "// Phase normalization (the SciPy default) is the only norm scir-signal's\n"
        "// public wrapper exposes today. Each inner slice is the analog-prototype\n"
        "// pole list as `(real, imag)` pairs; zeros are always empty and the gain\n"
        "// is always 1.0 for the phase norm.\n"
        "//\n"
        "// IEEE f64 round-trips losslessly via {:.17e} formatting.\n"
        "\n"
        "/// Analog Bessel poles in phase normalization for orders 1..=25.\n"
        "/// Index 0 → N=1, index 1 → N=2, ..., index 24 → N=25.\n"
        "pub(crate) const BESSEL_AP_PHASE_POLES: [&[(f64, f64)]; 25] = [\n"
        f"{body}\n"
        "];\n"
    )
    OUT.write_text(src)
    print(f"wrote {OUT} ({MAX_ORDER} orders)")


if __name__ == "__main__":
    main()
