name: CI
on:
  push:
  pull_request:

jobs:
  python-fixtures:
    name: Python fixtures + checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Bash script syntax check
        run: bash -n scripts/*.sh
      - name: Run Python script compile test
        run: |
          pip install pytest
          pytest -q tests/test_scripts_compile.py
      - name: Generate fixtures
        run: |
          python scripts/gen_fixtures.py -n 8 16
          python scripts/gen_signal_fixtures.py
          python scripts/gen_optimize_fixtures.py
          python scripts/gen_linalg_fixtures.py
      - name: Upload fixtures
        uses: actions/upload-artifact@v4
        with:
          name: scir-fixtures
          path: fixtures/**

  rust-tests:
    name: Rust tests (matrix)
    runs-on: ${{ matrix.os }}
    needs: python-fixtures
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Setup vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v7
        with:
          triplet: x64-windows
          vcpkgArguments: install openblas
      - name: Configure vcpkg env (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          echo "VCPKGRS_DYNAMIC=1" >> $Env:GITHUB_ENV
          echo "VCPKG_DEFAULT_TRIPLET=x64-windows" >> $Env:GITHUB_ENV
      - name: Download fixtures
        uses: actions/download-artifact@v4
        with:
          name: scir-fixtures
          path: fixtures
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: cargo clippy --workspace --features "blas,linux-blas" -- -D warnings
      - name: Clippy (macOS)
        if: matrix.os == 'macos-latest'
        run: cargo clippy --workspace --features "blas,macos-accelerate" -- -D warnings
      - name: Clippy (Windows)
        if: matrix.os == 'windows-latest'
        run: cargo clippy --workspace --features "blas,windows-openblas" -- -D warnings
      - name: Build + Test (Linux, OpenBLAS static)
        if: matrix.os == 'ubuntu-latest'
        run: |
          cargo build --workspace --features "blas,linux-blas" --verbose
          cargo test  --workspace --features "blas,linux-blas" --verbose
      - name: Build + Test (macOS, Accelerate)
        if: matrix.os == 'macos-latest'
        run: |
          cargo build --workspace --features "blas,macos-accelerate" --verbose
          cargo test  --workspace --features "blas,macos-accelerate" --verbose
      - name: Build + Test (Windows, OpenBLAS via vcpkg)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          cargo build --workspace --features "blas,windows-openblas" --verbose
          cargo test  --workspace --features "blas,windows-openblas" --verbose
