name: CI
on:
  push:
  pull_request:

jobs:
  python-fixtures:
    name: Python fixtures + checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Bash script syntax check
        run: bash -n scripts/*.sh
      - name: Run Python script compile test
        run: |
          pip install pytest
          pytest -q tests/test_scripts_compile.py
      - name: Generate fixtures
        run: |
          python scripts/gen_fixtures.py -n 8 16
          python scripts/gen_signal_fixtures.py
          python scripts/gen_optimize_fixtures.py
          python scripts/gen_linalg_fixtures.py
      - name: Upload fixtures
        uses: actions/upload-artifact@v4
        with:
          name: scir-fixtures
          path: fixtures/**

  rust-tests:
    name: Rust tests (matrix)
    runs-on: ${{ matrix.os }}
    needs: python-fixtures
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Install sccache (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y sccache
      - name: Install sccache (macOS)
        if: matrix.os == 'macos-latest'
        run: brew update && brew install sccache
      - name: Install sccache (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: choco install sccache -y
      - name: Setup sccache env (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash
        run: |
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV
          if [ -n "${{ secrets.SCCACHE_BUCKET }}" ]; then echo "SCCACHE_BUCKET=${{ secrets.SCCACHE_BUCKET }}" >> $GITHUB_ENV; fi
          if [ -n "${{ secrets.SCCACHE_REGION }}" ]; then echo "SCCACHE_REGION=${{ secrets.SCCACHE_REGION }}" >> $GITHUB_ENV; fi
          TRIPLE=$(rustc -vV | sed -n 's/^host: //p')
          echo "SCCACHE_S3_KEY_PREFIX=/scir/${TRIPLE}" >> $GITHUB_ENV
      - name: Setup sccache env (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          "RUSTC_WRAPPER=sccache" | Out-File -FilePath $env:GITHUB_ENV -Append
          if ('${{ secrets.SCCACHE_BUCKET }}' -ne '') { "SCCACHE_BUCKET=${{ secrets.SCCACHE_BUCKET }}" | Out-File -FilePath $env:GITHUB_ENV -Append }
          if ('${{ secrets.SCCACHE_REGION }}' -ne '') { "SCCACHE_REGION=${{ secrets.SCCACHE_REGION }}" | Out-File -FilePath $env:GITHUB_ENV -Append }
          $triple = (& rustc -vV) -split "`n" | Where-Object { $_ -like 'host: *' } | ForEach-Object { ($_ -split ':')[1].Trim() }
          "SCCACHE_S3_KEY_PREFIX=/scir/$triple" | Out-File -FilePath $env:GITHUB_ENV -Append
      - name: Start sccache server
        run: sccache --start-server || true
      - name: Warm sccache (quick check)
        shell: bash
        env:
          CARGO_TARGET_DIR: target-warm
        run: |
          # Build a couple of small crates to populate cache
          cargo check -p scir-core -p scir-nd -p scir-fft -q || true
      - uses: Swatinem/rust-cache@v2
      - name: Setup vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        uses: johnwason/vcpkg-action@v7
        with:
          pkgs: openblas
          triplet: x64-windows
          token: ${{ github.token }}
          extra-args: --clean-after-build
      - name: Configure vcpkg env (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          "VCPKGRS_DYNAMIC=1" | Out-File -FilePath $env:GITHUB_ENV -Append
          "VCPKG_DEFAULT_TRIPLET=x64-windows" | Out-File -FilePath $env:GITHUB_ENV -Append
          if ($env:VCPKG_INSTALLATION_ROOT) { "VCPKG_ROOT=$($env:VCPKG_INSTALLATION_ROOT)" | Out-File -FilePath $env:GITHUB_ENV -Append }
      - name: Verify vcpkg (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          echo "VCPKG_ROOT=$env:VCPKG_ROOT"
          vcpkg list || echo "vcpkg list failed (will rely on env vars)"
      - name: Ensure OpenBLAS via vcpkg (Windows fallback)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          $triplet = "x64-windows"
          $installed = (vcpkg list 2>$null) | Select-String -Pattern "^openblas\s" -Quiet
          if (-not $installed) {
            if ($env:VCPKG_ROOT -and (Test-Path "$env:VCPKG_ROOT\vcpkg.exe")) {
              & "$env:VCPKG_ROOT\vcpkg.exe" install "openblas:$triplet" || exit 1
            } elseif ($env:VCPKG_INSTALLATION_ROOT -and (Test-Path "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe")) {
              & "$env:VCPKG_INSTALLATION_ROOT\vcpkg.exe" install "openblas:$triplet" || exit 1
            } else {
              Write-Host "Attempting vcpkg from PATH"
              vcpkg install "openblas:$triplet" || exit 1
            }
          } else {
            Write-Host "OpenBLAS already installed in vcpkg"
          }
      - name: Download fixtures
        uses: actions/download-artifact@v4
        with:
          name: scir-fixtures
          path: fixtures
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Clippy workspace (all OS, exclude linalg)
        env:
          CARGO_TARGET_DIR: target-ws
        run: cargo clippy --workspace --all-targets --exclude scir-linalg -- -D warnings
      - name: Clippy scir-linalg (Linux)
        if: matrix.os == 'ubuntu-latest'
        env:
          CARGO_TARGET_DIR: target-linalg-linux
        run: cargo clippy --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "blas,linux-blas" -- -D warnings
      - name: Clippy scir-linalg (macOS)
        if: matrix.os == 'macos-latest'
        env:
          CARGO_TARGET_DIR: target-linalg-macos
        run: cargo clippy --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "faer" -- -D warnings
      - name: Clippy scir-linalg (Windows)
        if: matrix.os == 'windows-latest'
        env:
          CARGO_TARGET_DIR: target-linalg-windows
        run: cargo clippy --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "blas,windows-openblas" -- -D warnings
      - name: Build + Test core crates (no BLAS)
        env:
          CARGO_TARGET_DIR: target-core
        run: |
          for pkg in scir-core scir-nd scir-fft scir-signal scir-optimize; do \
            echo "::group::build $pkg"; cargo build -p $pkg --verbose; echo "::endgroup::"; \
            echo "::group::test  $pkg"; cargo test  -p $pkg --verbose; echo "::endgroup::"; \
          done
      - name: Build + Test scir-linalg (Linux, OpenBLAS static)
        if: matrix.os == 'ubuntu-latest'
        env:
          CARGO_TARGET_DIR: target-linalg-linux
        run: |
          cargo build --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "blas,linux-blas" --verbose
          cargo test  --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "blas,linux-blas" --verbose
      - name: Build scir-linalg (macOS, faer)
        if: matrix.os == 'macos-latest'
        env:
          CARGO_TARGET_DIR: target-linalg-macos
        run: cargo build --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "faer" --verbose
      - name: Build + Test scir-linalg (Windows, OpenBLAS via vcpkg)
        if: matrix.os == 'windows-latest'
        shell: bash
        env:
          CARGO_TARGET_DIR: target-linalg-windows
        run: |
          cargo build --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "blas,windows-openblas" --verbose
          cargo test  --manifest-path crates/scir-linalg/Cargo.toml -p scir-linalg --features "blas,windows-openblas" --verbose
      - name: sccache stats
        if: always()
        run: sccache --show-stats || true
