# Continuous integration pipeline building, linting, testing, and cross-compiling embedded examples.
name: CI
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker.io/iraa/rlvgl:latest
      # Start as your non-root user right away
      # options: --user ${{ vars.RLVGL_BUILDER_USER }}

    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: bash scripts/setup-ci-env.sh
      - run: cargo build --workspace --verbose
      - run: cargo fmt --all -- --check
      - run: cargo clippy --workspace -- -D warnings
      - run: cargo test --workspace --target x86_64-unknown-linux-gnu --verbose
      - run: RUSTDOCFLAGS="--cfg docsrs --cfg nightly" cargo +nightly doc --all-features --no-deps --target x86_64-unknown-linux-gnu

  stm32h747i-disco:
    runs-on: ubuntu-latest
    container:
      image: docker.io/iraa/rlvgl:latest

    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: bash scripts/setup-ci-env.sh
      - name: Install target
        run: rustup target add thumbv7em-none-eabihf
      - name: Build firmware
        run: RUSTFLAGS="" cargo build --bin rlvgl-stm32h747i-disco --features "stm32h747i_disco,qrcode,png,jpeg,fontdue" --target thumbv7em-none-eabihf --release
      - name: Firmware size
        run: arm-none-eabi-size target/thumbv7em-none-eabihf/release/rlvgl-stm32h747i-disco | tee size.txt
      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: rlvgl-stm32h747i-disco
          path: |
            target/thumbv7em-none-eabihf/release/rlvgl-stm32h747i-disco
            size.txt

  stm32h747i-disco-fatfs:
    continue-on-error: true
    runs-on: ubuntu-latest
    container:
      image: docker.io/iraa/rlvgl:latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: bash scripts/setup-ci-env.sh
      - name: Install target
        run: rustup target add thumbv7em-none-eabihf
      - name: Build firmware (fatfs no_std demo)
        run: |
          RUSTFLAGS="" cargo build \
            --bin rlvgl-stm32h747i-disco \
            --features "stm32h747i_disco,fatfs_nostd,sd_assets_demo" \
            --target thumbv7em-none-eabihf --release || true

  polish:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    container:
      image: docker.io/iraa/rlvgl:latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: bash scripts/setup-ci-env.sh
      - name: Run polish
        run: bash scripts/pre-commit.sh

  chipdb:
    runs-on: ubuntu-latest
    container:
      image: docker.io/iraa/rlvgl:latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: bash scripts/setup-ci-env.sh
      - name: Generate vendor databases
        run: tools/build_vendor.sh
      - name: Build vendor crate
        env:
          RLVGL_CHIP_SRC: chipdb/rlvgl-chips-stm/generated
        run: cargo build -p rlvgl-chips-stm

  boards:
    runs-on: ubuntu-latest
    container:
      image: docker.io/iraa/rlvgl:latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare build environment
        run: bash scripts/setup-ci-env.sh
      - name: Build STM32 board database
        run: bash scripts/stm32_afdb_pipeline.sh
      - name: Upload boards.json
        uses: actions/upload-artifact@v4
        with:
          name: boards-json
          path: chipdb/rlvgl-chips-stm/db/boards.json
