# Publishes crates to crates.io when a release tag is pushed or the workflow is manually dispatched.
name: Publish

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      base:
        description: "Base SHA (e.g., previous release tag commit)"
        required: true
      head:
        description: "Head SHA (e.g., tagged commit on main)"
        required: true

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    if: >
      github.event_name == 'workflow_dispatch' ||
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout tagged commit (or manual head)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.sha }}
          submodules: recursive

      - name: Resolve base/head SHAs
        id: shas
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "base=${{ github.event.inputs.base }}" >> $GITHUB_OUTPUT
            echo "head=${{ github.event.inputs.head }}" >> $GITHUB_OUTPUT
          else
            prev_tag="$(git describe --tags --abbrev=0 "${GITHUB_SHA}^" 2>/dev/null || echo "")"
            if [[ -n "$prev_tag" ]]; then
              base="$(git rev-parse "$prev_tag")"
            else
              base="$(git rev-list --max-parents=0 "$GITHUB_SHA")"
            fi
            echo "base=$base" >> $GITHUB_OUTPUT
            echo "head=$GITHUB_SHA" >> $GITHUB_OUTPUT
          fi

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Publish changed crates
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: bash scripts/publish_changed.sh ${{ steps.shas.outputs.base }} ${{ steps.shas.outputs.head }}
