name: publish
on:
  push:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - name: Determine base ref
        id: base
        shell: bash
        run: |
          # Prefer the event.before SHA; fall back to origin/main~1
          base_ref="${{ github.event.before }}"
          if [[ -z "$base_ref" || "$base_ref" == "0000000000000000000000000000000000000000" ]]; then
            base_ref="origin/main~1"
          fi
          echo "base=$base_ref" >> $GITHUB_OUTPUT
      - name: Publish changed crates in order
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: scripts/publish_changed.sh "${{ steps.base.outputs.base }}"
